config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#main'
  get '/app', to: 'scenarios#index', as: 'app'
  get '/guide', to: 'pages#guide', as: 'guide'
  get '/terms', to: 'pages#terms'
  get '/about', to: 'pages#about'

  devise_for :users, :controllers => {:registrations => 'users/registrations'}

  namespace :admin do
    root 'pages#main'
    put '/organisation', to: 'pages#update_organisation_name'

    get '/scenarios/:scenario_id', to: 'pages#get_scenario'
    get '/scenarios/:scenario_id/users/:user_id', to: 'pages#get_attempts'
    get '/scenarios/:scenario_id/users/:user_id/results/:result_id', to: 'pages#get_result'

    get '/users/:user_id', to: 'pages#get_user'
    put '/users/:user_id/approve', to: 'pages#approve_user'
    put '/users/:user_id/admin', to: 'pages#set_admin'
    delete '/users/:user_id', to: 'pages#delete_user', as: :delete_user
  end

  resources :scenarios do
    resources :questions do
      resources :answers
    end
  end

  post 'start_scenario', to: 'attempts#start_scenario'
  put 'resume_scenario', to: 'attempts#resume_scenario'
  put 'select_answer', to: 'attempts#select_answer'
  get '/scenarios/:scenario_id/results/:attempt_id', to: 'results#show', as: 'show_results'

end

app/models/question.rb
# app/models/question.rb
class Question < ApplicationRecord
  belongs_to :scenario
  belongs_to :user
  has_many :answers, dependent: :destroy, foreign_key: :question_id
end

app/controllers/questions_controller.rb
# app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_scenario
  before_action :set_question, except: %i[new create index]
  before_action :set_attempt, :verify_attempt, :verify_question, only: :show
  before_action :require_admin, except: :show

  # GET /scenarios/:scenario_id/questions
  def index
    @questions = Question.all.where(scenario_id: @scenario.id)
    respond_to do |format|
      format.html
      # TODO: Improve this query
      format.json { json_response(@questions.as_json(include: :answers)) }
    end
  end

  # GET /scenarios/:scenario_id/questions/:id
  def show
    respond_to do |format|
      format.html
      # TODO: Improve this query
      format.json { json_response(@question.as_json(include: :answers)) }
    end
  end

  # GET /scenarios/:scenario_id/questions/new
  def new
    @question = Question.new
    @question_orders = question_orders
    @next_question_order = @question_orders.present? ? @question_orders.max + 1 : 0
  end

  # POST /scenarios/:scenario_id/questions
  def create
    if (@question = current_user.questions.create!(question_params.merge(scenario_id: @scenario.id)))
      respond_to do |format|
        format.html { redirect_to scenario_path(@question.scenario_id, anchor: "question_order_#{@question.order}") }
        format.json { json_response(@question.as_json, :created) }
      end
    else
      respond_to do |format|
        format.html { render 'new' } # when new exists render new
        format.json { json_response(@question.errors) }
      end
    end
  end

  # GET /scenarios/:scenario_id/questions/:id/edit
  def edit
    @question_orders = question_orders
    @next_question_order = @question_orders.max + 1
  end

  # PUT /scenarios/:scenario_id/questions/:id
  def update
    if @question.update(question_params)
      respond_to do |format|
        format.html { redirect_to scenario_path(@question.scenario_id, anchor: "question_order_#{@question.order}") }
        format.json { json_response(@question, :no_content) }
      end
    else
      respond_to do |format|
        format.html { render 'edit' } # when new exists render new
        format.json { json_response(@question.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /scenarios/:scenario_id/questions/:id
  def destroy
    if @question.destroy
      respond_to do |format|
        format.html { redirect_to scenario_path(@question.scenario_id) }
        format.json { json_response(@question, :no_content) }
      end
    end
  end

  private

  def verify_attempt
    return unless @attempt.nil? || @attempt.completed

    redirect_to scenario_path(@scenario),
                notice: 'You need to start or resume a scenario to view its questions'
  end

  def verify_question
    return unless @question.id != @attempt.next_question_id && !@attempt.been_answered?(@question.id)

    redirect_to scenario_question_path(@scenario, @attempt.next_question_id),
                notice: 'This is the question you should be answering'
  end

  def set_scenario
    @scenario = if current_user.admin?
                  current_user.organisation.scenarios.find(params[:scenario_id])
                else
                  current_user.organisation.scenarios.available.find(params[:scenario_id])
                end
  end

  def set_question
    @question = @scenario.questions.find(params[:id])
  end

  def set_attempt
    @attempt = Attempt.where('user_id = ?', current_user.id).find(session["scenario_id_#{@scenario.id}_attempt_id"])
  rescue ActiveRecord::RecordNotFound
    redirect_to scenario_path(@scenario),
                notice: 'You need to start or resume a scenario to view its questions'
  end

  def question_params
    # whitelist params
    params.require(:question).permit(:order, :text, :description, :scenario_id)
  end

  def question_orders
    @scenario.questions.map(&:order)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="row builder-form">
  <%= form_for question, url: { action: action } do |form| %>
    <% if question.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

        <ul>
          <% question.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field mb-3">
      <%= form.label :description, class: "form-label" %>
      <i class="fas fa-question-circle collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#questionDescriptionHint" aria-expanded="false" aria-controls="scenarioNameHint"></i>
      <div class="collapse hint-box" id="questionDescriptionHint">
        This is the question description. Use this to describe the current situation that the participant is facing.
        Provide exposition and context to help the participant understand the choice which they are about to make.
      </div>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :text, class: "form-label" %>
      <i class="fas fa-question-circle collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#questionTextHint" aria-expanded="false" aria-controls="scenarioNameHint"></i>
      <div class="collapse hint-box" id="questionTextHint">
        This is the question text. This is the exact question which the participant needs to answer. Often this will be
        something like "What do you do?".
      </div>
      <%= form.text_field :text, class: "form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :order, class: "form-label" %>
      <i class="fas fa-question-circle collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#questionOrderHint" aria-expanded="false" aria-controls="scenarioNameHint"></i>
      <div class="collapse hint-box" id="questionOrderHint">
        <p>This is used to uniquely identify questions within the flow of the scenario. It doesn't indicate the order
          which a participant will see questions, it just provides the reference for an answer to link to. Each answer
          will store the "Next Question Order" value, providing the link to the next question that follows the selected
          answer. Each question in a scenario must have a unique "order" value. </p>
        <p>The first question of the scenario should have an order of "0". You will need to set one question to have
          this order value before the scenario can be attempted.</p>
      </div>
      <% if @question_orders.present? %>
        <div>
          <p class="mb-0">Current used question orders: <b><%= @question_orders.to_sentence %></b></p>
          <p class="mb-0">Next available order: <b><%= @next_question_order %></b></p>
          <p>Unused values in current range: <b><%= ((@question_orders.min..@question_orders.max).to_a - @question_orders).to_sentence %></b></p>
        </div>
      <% end %>
      <%= form.number_field :order, class: "form-control", required: true, value: question.order || @next_question_order %>
    </div>

    <div class="actions text-center">
      <%= form.submit nil, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<section class="admin-view">
  <div class="container">
    <h1 class="text-center">Editing Question</h1>

    <%= render 'form', question: @question, action: "update" %>

    <div class="text-center my-2">
      <%= link_to 'Destroy', scenario_question_path(@question.scenario_id, @question.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
    </div>
    <div class="text-center">
      <%= link_to 'Show', scenario_question_path(@question.scenario_id, @question.id) %> |
      <%= link_to 'Back', scenario_path(@question.scenario_id, anchor: "question_order_#{@question.order.to_s}") %>
    </div>
  </div>
</section>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>
<section class="text-center">
  <div class="container">
    <div class="row">


      <h1>Scenario: <%= @scenario.id %></h1>
      <h3><%= @scenario.name %></h3>
      <h5><%= @scenario.description %></h5>
      <h1>Questions</h1>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <% @questions.each do |question| %>
      <div id="question_order_<%= question.order %>" class="row justify-content-md-center shadow p-3 mb-5 bg-white rounded">
        <p><strong>Order: </strong><%= question.order %></p>
        <p><strong>Description: </strong><%= question.description %></p>
        <p><strong>Text: </strong><%= question.text %></p>
        <p><strong>Answers:</strong></p>
        <table>
          <tbody>
          <% question.answers.each do |answer| %>
            <tr>
              <td><%= answer.text %></td>
              <td>
                Next Question: <a href="#question_order_<%= answer.next_question_order %>">
                Order <%= answer.next_question_order %>
              </a>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</section>

<section>
  <div class="container">
    <div class="row justify-content-md-center shadow p-3 mb-5 bg-white rounded">
      <table>
        <thead>
        <tr>
          <th>Description</th>
          <th>Text</th>
          <th>Order</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @questions.each do |question| %>
          <tr>
            <td><%= question.description %></td>
            <td><%= question.text %></td>
            <td><%= question.order %></td>
            <td><%= link_to 'Show', scenario_question_path(question.scenario_id, question.id) %></td>
            <td><%= link_to 'Edit', edit_scenario_question_path(question.scenario_id, question.id) %></td>
            <td><%= link_to 'Destroy', scenario_question_path(question.scenario_id, question.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>
<br>

<%= link_to 'New Question', new_scenario_question_path(@scenario) %>

app/views/questions/new.html.erb
<section class="admin-view">
  <div class="container">
    <h1 class="text-center">New Question</h1>

    <%= render 'form', question: @question, action: "create" %>

    <div class="text-center">
      <%= link_to 'Back', scenario_path(@scenario.id) %>
    </div>
  </div>
</section>

app/views/questions/show.html.erb
<section class="scenario-header text-center">
  <div class="container scenario-show-container shadow rounded-3">
    <div class="row">
      <h2 class="scenario-heading"> <%= simple_format(@question.description) %> </h2>
      <p> <%= @question.text %> </p>
    </div>

    <% @question.answers.each do |answer| %>
      <%= link_to select_answer_url(answer_id: answer.id), data: { method: "put" }, class:"text-decoration-none" do %>
        <div class="row justify-content-md-center answer-row">
          <div class="col question-answer">
            <p> <%= answer.text %> </p>
          </div>
        </div>
      <% end %>
    <% end %>

  </div>
</section>