config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#main'
  get '/app', to: 'scenarios#index', as: 'app'
  get '/guide', to: 'pages#guide', as: 'guide'
  get '/terms', to: 'pages#terms'
  get '/about', to: 'pages#about'

  devise_for :users, :controllers => {:registrations => 'users/registrations'}

  namespace :admin do
    root 'pages#main'
    put '/organisation', to: 'pages#update_organisation_name'

    get '/scenarios/:scenario_id', to: 'pages#get_scenario'
    get '/scenarios/:scenario_id/users/:user_id', to: 'pages#get_attempts'
    get '/scenarios/:scenario_id/users/:user_id/results/:result_id', to: 'pages#get_result'

    get '/users/:user_id', to: 'pages#get_user'
    put '/users/:user_id/approve', to: 'pages#approve_user'
    put '/users/:user_id/admin', to: 'pages#set_admin'
    delete '/users/:user_id', to: 'pages#delete_user', as: :delete_user
  end

  resources :scenarios do
    resources :questions do
      resources :answers
    end
  end

  post 'start_scenario', to: 'attempts#start_scenario'
  put 'resume_scenario', to: 'attempts#resume_scenario'
  put 'select_answer', to: 'attempts#select_answer'
  get '/scenarios/:scenario_id/results/:attempt_id', to: 'results#show', as: 'show_results'

end

app/models/answer.rb
# app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  before_create :update_next_question_id
  before_update :update_next_question_id

  def update_variable_mods
    question.scenario.variables.each { |variable| self.variable_mods.store(variable, 0) unless self.variable_mods.include? variable }
    self.variable_mods.each { |key, value| self.variable_mods.delete(key) unless question.scenario.variables.include? key }
    self.save
  end

  private

  def update_next_question_id
    return unless next_question_order? && next_question_order != -1

    self.next_question_id = question.scenario.questions.find_by!(order: next_question_order).id
  end

  # validations
  validates_presence_of :text, :user_id, :question_id
  validate :valid_variable_mods

  def valid_variable_mods
    return true if variable_mods.blank?

    valid_variables = Scenario.find(Question.find(question_id).scenario_id).variables
    invalid_keys = variable_mods.keys - valid_variables

    return if variable_mods.keys.all? { |s| valid_variables.include? s }

    errors.add(invalid_keys.to_s, 'are not valid variables')
  end
end

app/controllers/answers_controller.rb
# app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, :set_variables
  before_action :set_answer, only: %i[edit update destroy]
  before_action :require_admin

  # GET /scenarios/:scenario_id/questions/:question_id/answers/new
  def new
    @answer = Answer.new
  end

  # POST /scenarios/:scenario_id/questions/:question_id/answers
  def create
    if (@answer = current_user.answers.create!(answer_params.merge(question_id: @question.id)))
      respond_to do |format|
        format.html { redirect_to scenario_path(@question.scenario_id, anchor: "question_order_#{@question.order.to_s}") }
        format.json { json_response(@answer, :created) }
      end
    end
  end

  # GET /scenarios/:scenario_id/questions/:question_id/answers/:id
  def edit
    @answer
  end

  # PUT /scenarios/:scenario_id/questions/:question_id/answers/:id
  def update
    if @answer.update(answer_params)
      respond_to do |format|
        format.html { redirect_to scenario_path(@question.scenario_id, anchor: "question_order_#{@question.order}") }
        format.json { json_response(@answer, :ok) }
      end
    end
  end

  # DELETE /scenarios/:scenario_id/questions/:question_id/answers/:id
  def destroy
    if @answer.destroy
      respond_to do |format|
        format.html { redirect_to scenario_path(@question.scenario_id, anchor: "question_order_#{@question.order}") }
        format.json { json_response(nil, :no_content) }
      end
    end
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_variables
    @variables = Scenario.find(params[:scenario_id]).variables
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    # whitelist params
    # variables = Scenario.find(params[:scenario_id]).variables.map { |v| [v.to_sym] }
    params.require(:answer).permit(:text, :next_question_order, :question_id, variable_mods: {})
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<div class="row">
  <%= form_for answer, id: 'answer_form', url: { action: action } do |form| %>
    <% if answer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

        <ul>
          <% answer.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field mb-3">
      <%= form.label :text, class: "form-label" %>
      <i class="fas fa-question-circle collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#answerTextHint" aria-expanded="false" aria-controls="scenarioNameHint"></i>
      <div class="collapse hint-box" id="answerTextHint">
        This is the text of the answer. This should describe what the participant is doing in the scenario by selecting
        the answer.
      </div>
      <%= form.text_field :text, class: "form-control" %>
    </div>

    <div class="field mb-3 justify-content-center">
      <%= form.label :variable_mods %>
      <i class="fas fa-question-circle collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#answerVariablesHint" aria-expanded="false" aria-controls="scenarioNameHint"></i>
      <div class="collapse hint-box" id="answerVariablesHint">
        These are the variable modifiers that will be applied should this answer be selected. They need to be whole
        numbers but can be positive or negative. If you don't want to change any of them then you can just leave them
        blank.
      </div>
      <table>
        <% @variables&.each do |variable| %>
          <tr>
            <td>
              <label for='answer[variable_mods][<%= variable %>]' class='form-label'><%= variable %>: </label>
            </td>
            <td>
              <input multiple='multiple' type='number'
                     value='<%= answer.variable_mods[variable] if answer.variable_mods.present? && answer.variable_mods.has_key?(variable) %>'
                     name='answer[variable_mods][<%= variable %>]'
                     placeholder='<%= variable %>'
                     class='form-control'>
            </td>
          </tr>
        <% end %>
      </table>
    </div>

    <div id="next_question_order_container">
      <div class="field mb-3" id="next_question_order">
        <%= form.label :next_question_order, class: "form-label" %>
        <i class="fas fa-question-circle collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#answerOrderHint" aria-expanded="false" aria-controls="scenarioNameHint"></i>
        <div class="collapse hint-box" id="answerOrderHint">
          This is the question which this answer will lead to. You can leave it blank and update it later if you haven't
          created the next question yet or if you're unsure.
        </div>
        <%= form.number_field :next_question_order, class: "form-control" %>
      </div>

      <div class="mb-2 text-center">
        <i class="fas fa-question-circle color-transparent"></i>
        <button type="button"
                id="end_scenario_button"
                class="btn btn-sm btn-outline-warning">
          End of Scenario <span id="end_of_quiz_icon"></span>
        </button>
        <i class="fas fa-question-circle color-orange"
           data-bs-toggle="tooltip"
           data-bs-placement="right"
           data-bs-html="true"
           title="Toggle whether or not this question leads to the end of the scenario."></i>
      </div>

    </div>

    <div class="actions text-center">
      <%= form.submit nil, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<%= javascript_pack_tag 'erb_form_functions' %>

app/views/answers/edit.html.erb
<section class="admin-view">
  <div class="container">

    <h1 class="text-center">Editing Answer</h1>

    <%= render 'form', answer: @answer, action: "update" %>

    <div class="text-center my-2">
      <%= link_to 'Destroy', scenario_question_answer_path(@question.scenario_id, @question.id, @answer), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
    </div>
    <div class="text-center">
    <%= link_to 'Back', scenario_path(@question.scenario_id, anchor: "question_order_#{@question.order.to_s}") %>
    </div>
  </div>
</section>

app/views/answers/new.html.erb
<section class="admin-view">
  <div class="container">

    <h1 class="text-center">New Answer</h1>

    <%= render 'form', answer: @answer, action: "create" %>

    <div class="text-center">
    <%= link_to 'Back', scenario_path(@question.scenario_id, anchor: "question_order_#{@question.order.to_s}") %>
    </div>
  </div>
</section>