config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#main'
  get '/app', to: 'scenarios#index', as: 'app'
  get '/guide', to: 'pages#guide', as: 'guide'
  get '/terms', to: 'pages#terms'
  get '/about', to: 'pages#about'

  devise_for :users, :controllers => {:registrations => 'users/registrations'}

  namespace :admin do
    root 'pages#main'
    put '/organisation', to: 'pages#update_organisation_name'

    get '/scenarios/:scenario_id', to: 'pages#get_scenario'
    get '/scenarios/:scenario_id/users/:user_id', to: 'pages#get_attempts'
    get '/scenarios/:scenario_id/users/:user_id/results/:result_id', to: 'pages#get_result'

    get '/users/:user_id', to: 'pages#get_user'
    put '/users/:user_id/approve', to: 'pages#approve_user'
    put '/users/:user_id/admin', to: 'pages#set_admin'
    delete '/users/:user_id', to: 'pages#delete_user', as: :delete_user
  end

  resources :scenarios do
    resources :questions do
      resources :answers
    end
  end

  post 'start_scenario', to: 'attempts#start_scenario'
  put 'resume_scenario', to: 'attempts#resume_scenario'
  put 'select_answer', to: 'attempts#select_answer'
  get '/scenarios/:scenario_id/results/:attempt_id', to: 'results#show', as: 'show_results'

end

app/views/pages/about.html.erb
<section id="" class="min-vh-100 info-page">
  <div class="text-container">
    <div class="row">
      <div class="col">
        <h1 class="text-center">About</h1>
        <p class="lead">The Scenario Platform allows the creation of non-linear branching scenarios where each answer that a
          participant selects can influence a range of background variables and link to an arbitrary next question.</p>

        <p>The idea was initially scoped for trainee solicitors to practise interview scenarios. As the project
          developed there was a wider demand beyond the original scope. The current platform should be diverse enough to
          be used in other areas such as rehabilitation, medical scenarios and customer service training.</p>

        <p>If you're interested in a <strong>demo</strong> of the software, finding out more or setting up your organisation on
          the platform then please <a href="mailto:sceanario-platform@legaltech.wales">send us an email</a>.</p>

        <p>If you're looking for more information on how to build scenarios then we have a <%= link_to 'Guide', guide_path %>
          which will hopefully help. </p>

        <p>This is an early prototype, we know its a little rough around the edges and there is lots of room for improvement. If you have any suggestions as to how we can improve it, the please get in touch and let us know.</p>

        <div>
          <h3>Coming Soon</h3>
          Some of the improvements we have planned include:
          <ul>
            <li>Add warning on making scenario available if its incomplete.</li>
            <li><s class="text-muted">Add hints and tips to create and update forms, and around the scenario builder</s> Added on 12th March</li>
            <li>Improving the look and feel of the emails you receive</li>
            <li><s class="text-muted">Admins receive an email when they have new members to confirm in their organisation</s> Added on 12th March</li>
            <li>Improvements to management of your organisation</li>
            <li><s class="text-muted">Admins can delete users from their organisation</s> Added on 12th March</li>
            <li><s class="text-muted">Admins should not be able to remove their own admin rights</s> Added on 12th March</li>
            <li><s class="text-muted">Improvements of the admin view on mobile</s> Added on 14th March</li>
            <li>Allowing Multi-select answers</li>
            <li>Allow more formatting of scenario and question descriptions</li>
            <li>Improve error message when invalid question order is added</li>
            <li><s class="text-muted">Provide more information to make it easier to set question order</s> Added on 12th March</li>
            <li><s class="text-muted">Make it easier to add final question in scenario (no more "-1")</s> Added on 12th March</li>
            <li>Warning on making scenario available if there are unlinked answers</li>
            <li>Allow or disable back-tracking for each scenario</li>
            <li>Fix a bug when trying to delete a scenario which has been attempted previously</li>
            <li>Add pagination for scenario attempts</li>
          </ul>
        </div>

        <% unless user_signed_in? %>
          <div class="text-center">
            <hr />
            <%= link_to 'Login', new_user_session_path, class: "btn btn-primary" %>
            <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-info" %>
            <%= link_to 'Home', root_path, class: "btn btn-secondary"  %>
            <hr />
          </div>
        <% end %>

        <div class="the-lab">
          <p class="lead">The Scenario Platform was created by the Legal Innovation Lab Wales which is an ERDF funded project and part of the Hillary
            Rodham Clinton School of Law at Swansea University.</p>
          <div class="text-center">
            <a href="https://legaltech.wales" class="btn btn-outline-info">Visit Our Site</a>
          </div>
          <div class="images mt-4 text-center">
            <%= image_tag 'LILW-SOL.png', class: 'lilw-logo' %>
            <%= image_tag 'erdf.png', class: 'erdf-logo' %>
          </div>

        </div>

      </div>
    </div>
  </div>
</section>

app/views/pages/guide.html.erb
<section id="" class="min-vh-100  info-page">
  <div class="text-container container">
    <div class="row">
      <div class="col">
        <h1 class="text-center">Guide</h1>
        <% unless user_signed_in? %>
          <div class="text-center">
            <hr/>
            <%= link_to 'Login', new_user_session_path, class: "btn btn-sm btn-primary" %>
            <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-sm btn-info" %>
            <%= link_to 'Home', root_path, class: "btn btn-sm btn-secondary" %>
            <hr/>
          </div>
        <% end %>
        <p class="lead">
          This guide is designed to give you some extra information on how scenarios work and to help you create them.
          It is a work in progress so please bear with us while we get it right. If you have any thoughts or
          suggestions, please let us know.
        </p>
        <div id="scenario">
          <h3>Scenario</h3>
          <p>
            The Scenario is the overall parent structure. When creating a new scenario it will need a name and a
            description. This description should be used to explain the scenario and provide background information to
            set the scene for participants.
          </p>
          <div class="lead">Variables</div>
          <p>
            The scenario will also need a set of variables which will be influenced by the participants chosen answers.
            These variables will not be visible to the participants until they complete the scenario and review their
            scores. There is no limit to how many there can be, but generally it's better to try and keep things as
            simple as possible.
          </p>
          <p>
            For example, these could contain values to represent how a character is feeling such as anger, fear,
            happiness, trust, and patience. All of these could be influenced in different ways by a participant’s chosen
            answers. Another example could be to represent stats relating to the participant such as health, strength,
            stamina, hunger, thirst and so on.
          </p>
          <div class="lead">Availability</div>
          <p>
            By default, new scenarios are not available for participants to complete. When you're happy that your
            scenario is complete you can edit it and hit the checkbox to make it available. At present there are no
            constraints on this action, so its down to you to check that everything is complete and working. When a
            scenario is under construction and not available it can still be completed by admin users in order to test
            it.
          </p>
        </div>

        <div id="question">
          <h3>Question</h3>
          <p>
            A scenario will be comprised of a set of questions. For each question you can add a long description and a
            short question text. The description will be displayed above the question text so could be used to provide
            more exposition or scene setting before using the question text field to ask the specific question which the
            participant will need to select an answer.
          <p>
            At present, the participant can only select one answer to a question, we will look to bring the option to
            select multiple answers in a future update. If you need to do this now, there is a
            <a href="#multi-select">workaround</a> at the bottom of this guide.
          </p>
          <div class="lead">Question Order</div>
          <p>
            Each question will also have a reference number, referred to in the app as "Question Order". This is used to
            uniquely identify questions within the flow of the scenario. Each answer will store the "Next Question
            Order" value, providing the link to the next question which the participant will see should they choose that
            answer. This enables branching and a more interactive experience where participants are lead down different
            paths. Each question in a scenario must have a unique "order" value.
          </p>
          <p>
            You can change the order of questions after they've been created. This is so you can expand branches or add
            new branches at any point. The scenario builder view will automatically order questions by their order
            value, so its worth bearing in mind that this might make some questions appear out of order.
          </p>
          <p>
            The first question of the scenario should have an order of "0". You will need to set one question to have
            this order value before the scenario can be attempted.
          </p>
          <div class="lead">Final Question</div>
          <p>
            Depending on the scenario you are building, there could be one or many final questions which act as the end
            of the scenario. These will be displayed before the final scores. To set an answer as the the end of a
            scenario, click the "End of Scenario" button on the answer form.When a user selects an answer which ends the
            scenario, the system will calculate the totals for the attempt and display the summary to the participant.
          </p>
          <p>
            There are two common ways of ending a scenario. You can either have the final question let the person know
            that the scenario is over and provide some context for what has happened. In this case we recommend that
            your "final question" only has one answer which takes the participant to their final scores. The other
            common pattern is to not let the person know that the scenario is going to end and just take them to their
            scores. The downside of this is that it doesn't provide any context.
          </p>
        </div>

        <div id="answer" class="mb-3">
          <h3>Answer</h3>
          <p>
            Each question can have as many answer choices as required. Each answer needs three things: some text to
            describe the choice, the changes to any variables as a consequence of selecting the answer, what the next
            question in the order will be. The next question and the variables which the answer influences will not be
            visible to the participant
          </p>

          <h5>Example</h5>
          <p><strong>Question Background:</strong> You have a 10.00 am appointment. At 10.00 am, there is a knock at the
            door while you are working on a different case file.</p>
          <p><strong>Question Text:</strong> You respond by:</p>

          <div>
            <div class="row justify-content-md-center answer-row">
              <div class="col question-answer">
                <p class="mb-0">
                  <strong>Answer:</strong>
                  <span class="lead">Ignoring the person at the door until you have finished the work you are doing</span>
                </p>
                <p><strong>Variable Changes</strong> (No changes)</p>
                <p><strong>Next Question</strong> [Question 4]</p>
              </div>
            </div>


            <div class="row justify-content-md-center answer-row">
              <div class="col question-answer">
                <p class="mb-0">
                  <strong>Answer:</strong>
                  <span class="lead">Answering the door, explaining that you are finishing up another case, and telling them that you will be with them at 10.15 am </span>
                </p>
                <p><strong>Variable Changes</strong> (No changes)</p>
                <p><strong>Next Question</strong> [Question 2]</p>
              </div>
            </div>

            <div class="row justify-content-md-center answer-row">
              <div class="col question-answer">
                <p class="mb-0">
                  <strong>Answer:</strong> <span class="lead">Calling out to come in</span>
                </p>
                <p><strong>Variable Changes</strong> (Fear increases by 1 point)</p>
                <p><strong>Next Question</strong> [Question 2]</p>
              </div>
            </div>

            <div class="row justify-content-md-center answer-row">
              <div class="col question-answer">
                <p class="mb-0">
                  <strong>Answer:</strong>
                  <span class="lead">Answering the door and asking them to come in</span>
                </p>
                <p><strong>Variable Changes</strong> (Trust increases by 1, Understanding increases by 1)</p>
                <p><strong>Next Question</strong> [Question 3]</p>
              </div>
            </div>
          </div>
        </div>

        <div id="quiz-builder">
          <h3>Quiz Builder</h3>
          <p>More info coming soon. What would you like to see here?</p>
        </div>

        <div id="multi-select">
          <h3>Multi-Select Question Work Around</h3>
          <p>If you really need to allow the participants to select multiple answers to a question you can write the
            options in the question description (EG. A, B, C, D). Then provide the combinations in the answer text. (EG.
            Answer 1: "A", Answer 2: "A + B", Answer 3: "A + B + C", Answer 4: "A + B + C + D", Answer 5: "B + C + D").
            Then each answer can influence the variables you wanted that selection to impact.</p>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/pages/main.html.erb
<section id="cover" class="<% if user_signed_in? %>homepage<% else %>min-vh-100<% end %>">
  <div class="sp-form">
    <div class="row text-white">
      <div class="mx-auto text-center form p-4">
        <h1 class="mb-3">Scenario Platform</h1>
        <p>An application created by the Legal Innovation Lab Wales for developing interactive scenarios</p>
        <div class="text-center">
          <% if user_signed_in? %>
            <%= link_to "Scenario App", app_path, class: "btn btn-sm btn-primary" %>
            <%= link_to "About This Project", about_path, class: "btn btn-sm btn-secondary"  %>
          <% else %>
            <%= link_to 'Login', new_user_session_path, class: "btn btn-sm btn-primary" %>
            <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-sm btn-info" %>
            <%= link_to "About This Project", about_path, class: "btn btn-sm btn-secondary"  %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/terms.html.erb
<section id="" class="min-vh-100 info-page">
  <div class="text-container container">
    <div class="row">
      <div class="col">

        <p>
          <span class="q">YOUR DATA</span> We're working to simplify privacy pages and make them as transparent and
          understandable as possible. This is what we do with your data and why.
        </p>

        <p>
          <span class="q">WHAT?</span> We collect and store the data that you add to the sign up form as well as data on
          your quiz attempts.
          <span class="q">WHY?</span> we do this to facilitate the core functionality of the app.
          <span class="q">HOW?</span> This data is stored in an encrypted database, and is encrypted in transit using SSL.
          <span class="q">WHO?</span> The data is only accessible to you, the admins of the organisation you are part of
          and our small team of developers at The <a href="https://legaltech.wales">Legal Innovation Lab Wales</a>.
          <span class="q">WHERE?</span> We use Heroku, Cloudflare, SendGrid and Netlify to power this application.
        </p>
        <p>
          <span class="q">Problems?</span> If any any point you are not happy with this you are welcome to delete your
          account or <a href="mailto:legalinnovation@swansea.ac.uk">contact the lab</a>.
          <span class="q">More?</span> If you want to find out more you can read our general
          <a href="https://media.legaltech.wales/docs/LILW-Privacy-Policy.pdf">privacy policy</a> which covers a broader
          scope of information than is used by this application.
        </p>

      </div>
    </div>
  </div>
</section>