config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#main'
  get '/app', to: 'scenarios#index', as: 'app'
  get '/guide', to: 'pages#guide', as: 'guide'
  get '/terms', to: 'pages#terms'
  get '/about', to: 'pages#about'

  devise_for :users, :controllers => {:registrations => 'users/registrations'}

  namespace :admin do
    root 'pages#main'
    put '/organisation', to: 'pages#update_organisation_name'

    get '/scenarios/:scenario_id', to: 'pages#get_scenario'
    get '/scenarios/:scenario_id/users/:user_id', to: 'pages#get_attempts'
    get '/scenarios/:scenario_id/users/:user_id/results/:result_id', to: 'pages#get_result'

    get '/users/:user_id', to: 'pages#get_user'
    put '/users/:user_id/approve', to: 'pages#approve_user'
    put '/users/:user_id/admin', to: 'pages#set_admin'
    delete '/users/:user_id', to: 'pages#delete_user', as: :delete_user
  end

  resources :scenarios do
    resources :questions do
      resources :answers
    end
  end

  post 'start_scenario', to: 'attempts#start_scenario'
  put 'resume_scenario', to: 'attempts#resume_scenario'
  put 'select_answer', to: 'attempts#select_answer'
  get '/scenarios/:scenario_id/results/:attempt_id', to: 'results#show', as: 'show_results'

end

app/models/scenario.rb
# app/models/scenario.rb
class Scenario < ApplicationRecord
  belongs_to :user
  delegate :organisation, to: :user, allow_nil: false

  has_many :questions, dependent: :destroy, foreign_key: :scenario_id
  has_many :answers, through: :questions
  has_many :attempts, foreign_key: :scenario_id
  has_many :users, -> { distinct }, through: :attempts

  scope :available, -> { where(available: true) }

  after_update :update_answers

  # validations
  validates_presence_of :user_id, :name, :description

  def first_question
    questions.find_by(order: 0)
  end

  private

  def update_answers
    return unless answers.present?

    answers.each(&:update_variable_mods)
  end
end

app/controllers/scenarios_controller.rb
# app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :set_scenario, only: %i[show update destroy]
  before_action :require_admin, only: %i[new create edit update delete]
  before_action :create_variables_hstore, only: %i[create update]

  # GET /scenarios
  def index
    @scenarios = set_scenarios

    respond_to do |format|
      format.html
      format.json { json_response(@scenarios) }
    end
  end

  # GET /scenarios/:id
  def show
    scenario = if current_user.admin?
                 @scenario.as_json(include: { questions: { include: :answers } })
               else
                 @scenario
               end
    @attempts = user_attempts
    respond_to do |format|
      format.html
      format.json { json_response(scenario) }
    end
  end

  # GET /scenarios/new
  def new
    @scenario = Scenario.new
  end

  # POST /scenarios
  def create
    if (@scenario = current_user.scenarios.create!(scenario_params.merge(variables_with_initial_values: create_variables_hstore)))
      respond_to do |format|
        format.html { redirect_to(@scenario) }
        format.json { json_response(@scenario, :created) }
      end
    end
  end

  # GET /scenarios/:id/edit
  def edit
    @scenario = Scenario.find(params[:id])
  end

  # PUT /scenarios/:id
  def update
    params = scenario_params.merge(variables_with_initial_values: create_variables_hstore) unless create_variables_hstore.nil?
    if @scenario.update!(params)
      respond_to do |format|
        format.html { redirect_to(@scenario) }
        format.json { json_response(@scenario, :no_content) }
      end
    end
  end

  # DELETE /scenarios/:scenario_id
  def destroy
    if @scenario.destroy
      respond_to do |format|
        format.html { redirect_to scenarios_path }
        format.json { json_response(@scenario, :no_content) }
      end
    end
  end

  private

  def set_scenarios
    if current_user.admin?
      current_user.organisation.scenarios
    else
      current_user.organisation.scenarios.available
    end
  end

  def set_scenario
    @scenario = if current_user.admin?
                  current_user.organisation.scenarios.find(params[:id])
                else
                  current_user.organisation.scenarios.available.find(params[:id])
                end
  end

  def user_attempts
    @scenario.attempts.where(user_id: current_user.id).order(:id)
  end

  def create_variables_hstore
    return unless params['scenario'].present?

    return unless params['scenario']['variables'].present? && params['scenario']['variable_initial_values'].present?

    vars = params['scenario']['variables']
    vals = params['scenario']['variable_initial_values']
    vars.zip(vals).to_h
  end

  def scenario_params
    # whitelist params
    params.require(:scenario).permit(:name, :description, :available, { variables: [] }, { variable_initial_values: [] }, variables_with_initial_values: {})
  end
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/_form.html.erb
<!--suppress ALL -->
<div class="row builder-form">
  <%= form_with(model: scenario, id: 'scenario_form') do |form| %>
    <% if scenario.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(scenario.errors.count, "error") %> prohibited this scenario from being saved:</h2>

        <ul>
          <% scenario.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field mb-3">
      <%= form.label :name, class: "form-label" %>
      <i class="fas fa-question-circle collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#scenarioNameHint" aria-expanded="false" aria-controls="scenarioNameHint"></i>
      <div class="collapse hint-box" id="scenarioNameHint">
        This is the name of your scenario. It should be allow participants to easily find the scenario they are looking
        for.
      </div>
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>

    <div class="field mb-3">
      <%= form.label :description, class: "form-label" %>
      <i class="fas fa-question-circle collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#scenarioDescriptionHint" aria-expanded="false" aria-controls="scenarioNameHint"></i>
      <div class="collapse hint-box" id="scenarioDescriptionHint">
        This is the description of your scenario. You should use this to provide general information about what the
        scenario is, you could also add some exposition to set the scene before participants attempt the scenario.
      </div>
      <%= form.text_area :description, class: "form-control", required: true %>
    </div>

    <div class="field mb-3 justify-content-center text-center">
      <div class="collapse hint-box mx-auto pb-2" id="scenarioVariablesHint">
        These are the variables which we will keep track of as each participant attempts this scenario. They can be used
        to keep track of any parameters or metrics you like. They are invisible to the participant until they complete
        their attempt, so the participant will not know which of their answers influenced the variables. Each answer
        that a participant selects can influence zero or many variables. The variable values can only be integers.
      </div>

      <table id="variables" class="mx-auto">
        <input type="hidden" value="<%= scenario.attempts.count %>" id="attempt_count">
        <tr>
          <th><%= form.label :variables, class: "form-label" %></th>
          <th><%= form.label :variable_initial_values, class: "form-label" %></th>
          <th>
            <i class="fas fa-question-circle collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#scenarioVariablesHint" aria-expanded="false" aria-controls="scenarioNameHint"></i>
          </th>
        </tr>

        <% unless scenario.variables_with_initial_values.present? %>
          <tr>
            <td><input multiple='multiple' type='text' name='scenario[variables][]' class="form-control" required></td>
            <td><input multiple='multiple' type='number' name='scenario[variable_initial_values][]' class="form-control" required></td>
            <td><button type="button" class="btn btn-sm btn-danger remove_variable">Remove</button></td>
          </tr>
        <% else %>
          <% scenario.variables_with_initial_values&.each do |variable| %>
            <tr>
              <td>
                <input multiple='multiple' type='text' value='<%= variable[0] %>' name='scenario[variables][]' class="form-control" required>
              </td>
              <td>
                <input multiple='multiple' type='number' value='<%= variable[1] %>' name='scenario[variable_initial_values][]' class="form-control" required>
              </td>
              <td>
                <button type="button" class="btn btn-sm btn-danger remove_variable">Remove</button>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>

      <div class="text-center">
        <button type="button" id="add_variable" class="btn btn-sm btn-success">Add</button>
      </div>
    </div>

    <div class="field mb-3 text-center">
      <div class="form-check form-switch text-center switch-success">
        <%= form.label :available, class: "form-check-label" %>
        <%= form.check_box :available, class: "form-check-input switch-success" %>
        <i class="fas fa-question-circle collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#scenarioAvailableHint" aria-expanded="false" aria-controls="scenarioNameHint"></i>
      </div>

      <div class="collapse hint-box" id="scenarioAvailableHint">
        This button makes your scenario available for any participant to complete. You should only switch it when you're
        happy that your scenario is complete.
      </div>
    </div>

    <div class="actions text-center">
      <%= form.submit nil, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<%= javascript_pack_tag 'erb_form_functions' %>

app/views/scenarios/edit.html.erb
<section class="admin-view">
  <div class="container">

    <h1 class="text-center">Editing Scenario</h1>

    <%= render 'form', scenario: @scenario %>

    <div class="text-center my-2">
      <%= link_to 'Destroy', scenario_path(@scenario.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
    </div>
    <div class="text-center">
      <%= link_to 'Show', @scenario %> |
      <%= link_to 'Back', scenarios_path %>
    </div>

  </div>
</section>

app/views/scenarios/index.html.erb
<section class="scenario-header scenario-index">
  <div class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="grey-transparent-bg col-lg-6 col-md-8 mx-auto">

        <h1>Scenarios</h1>
        <h4>Your organisation currently has <%= @scenarios.count %> scenarios</h4>
        <p>This is the interactive scenario homepage. Here you can view all the scenarios that are
          available to you. To view your past scores or to see more information about an scenario click the view
          button</p>

        <% if current_user.admin? %>
          <p>You can also create a new scenario here or edit an existing scenario below </p>
          <td><%= link_to 'Create New Scenario', new_scenario_path, class: "btn btn-lg btn-success" %></td>
        <% end %>
      </div>

    </div>
  </div>
</section>

<section class="scenario-album album py-5">

  <div class="container">
    <h1 class="text-center">All Scenarios</h1>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

      <% @scenarios.each do |scenario| %>
        <div class="col">
          <div class="card scenario-show-container shadow-sm h-100">
            <div class="card-body">
              <h3 class="text-center"><%= scenario.name %></h3>
              <p><%= simple_format(scenario.description) %></p>

            </div>

            <div class="card-footer  text-center">
              <% if current_user.admin? %>
                <p>Number of Attempts: <%= scenario.attempts.count %></p>
                <p>Available: <%= scenario.available %> </p>
              <% end %>

              <div class="btn-group">

                <%= link_to 'View', scenario_path(scenario), class: "btn btn-sm btn-info" %>
                <% if current_user.admin? %>
                  <%= link_to 'Edit', edit_scenario_path(scenario), class: "btn btn-sm btn-warning" %>

                <% else %>

                  <!--<button type="button" class="btn btn-sm btn-outline-secondary">Attempt</button>-->
                <% end %>

              </div>
            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</section>

app/views/scenarios/new.html.erb
<section class="admin-view">
  <div class="container">

    <h1 class="text-center">New Scenario</h1>

    <%= render 'form', scenario: @scenario %>

    <div class="text-center">
      <%= link_to 'Back', scenarios_path %>
    </div>
  </div>
</section>

app/views/scenarios/show.html.erb
<section class="scenario-header text-center">
  <div class="container scenario-show-container shadow rounded-3">
    <div class="row">
      <h1 class="scenario-heading"> <%= @scenario.name %> </h1>
      <p> <%= simple_format(@scenario.description) %> </p>

      <% if @scenario.questions.find_by(order: 0).present? %>

        <div class="text-center"><%= button_to "Start Scenario", start_scenario_url(scenario_id: @scenario), method: "post", class: "btn btn-success btn-lg" %></div>
      <% elsif current_user.admin? %>
        <h3> Please add a question with order 0 as a starting point for your scenario</h3>
      <% else %>
        <div class="text-center">
          <button class="btn btn-primary btn-large disabled">Start Scenario</button>
        </div>
      <% end %>
    </div>
  </div>
  <% if @attempts.present? %>
    <div class="container scenario-show-container shadow rounded-3">
      <div class="row">
        <h1 class="scenario-heading"> Previous Attempts </h1>
        <% @attempts.each do |attempt| %>
          <p class="mb-0"><strong><%= attempt.attempt_number.ordinalize %> Attempt.</strong></p>
          <% if attempt.scores.present? %>
            <p class="mb-0"><em>Scores: </em>
            <p>
              <% attempt.scores.each do |score| %><%= score[0].capitalize %>: <%= score[1] %>,
              <% end %></p>
          <% else %>
            <p>This attempt has not been completed.</p>
            <div class="text-center"><%= button_to "Resume Attempt", resume_scenario_url(attempt_id: attempt), method: "put", class: "btn btn-success btn-md" %></div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</section>

<% if current_user.admin? %>
  <section class="admin-view">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6 col-sm-10 admin-header align-self-center">
          <div class="card">
            <div class="card-body">
              <h2 class="text-danger text-center">Admin Only View</h2>
              <h2 class="text-center"><%= link_to "Edit Scenario", edit_scenario_path, class: "btn btn-warning btn-sm" %>
                <%= link_to "Guide", guide_path, class: "btn btn-primary btn-sm", target: :_blank %></h2>

              <table class="mx-auto">
                <tr>
                  <th colspan="2"><h5>Variables & Starting Values </h5></th>
                </tr>

                <% @scenario.variables.zip(@scenario.variable_initial_values) do |variable, variable_initial_value| %>
                  <tr class="text-start">
                    <td><%= variable %>:</td>
                    <td><%= variable_initial_value %></td>
                  </tr>
                <% end %>
              </table>

              <h2 class="text-center">
                <button class="btn btn-sm btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#attempts" aria-expanded="false" aria-controls="collapseHints">Show
                  Attempts Summary
                </button>
              </h2>
              <h2 class="text-center">
                <button class="btn btn-sm btn-info" type="button" data-bs-toggle="collapse" data-bs-target="#hints" aria-expanded="false" aria-controls="collapseHints">Show
                  Getting Started Hints
                </button>
              </h2>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="attempts" class="container collapse">
      <div class="row justify-content-md-center shadow-sm p-3 mb-5 bg-white rounded text-center">
        <h3>Scenario Attempts Summary</h3>
        <p><%= @scenario.attempts.count %> attempts by <%= @scenario.attempts.map { |u| [u.user_id] }.uniq.count %>
          Users</p>
        <p>Completed By:
        <ul class="list-unstyled">
          <% @scenario.attempts.map { |qa| [qa.user] }.uniq.each do |user| %>
            <li class="mb-0"><%= user[0].first_name %> <%= user[0].last_name %></li>
          <% end %>
        </ul>
        </p>

        <div class="mb-3"><%= link_to "Full Summary", admin_path(@scenario), class: "btn btn-outline-secondary" %></div>

        <hr>
        <p>This is still a prototype. If you have any thoughts about what else it could be useful to show here please
          let us know.</p>

      </div>
    </div>

    <div id="hints" class="container collapse">
      <div class="row justify-content-md-center shadow-sm p-3 mb-5 bg-white rounded text-center">
        <h3>Hints</h3>
        <div class="text-start">
          <h5>First things first</h5>
          <p>
            Add your first question. The first question of the scenario should have the order 0.
            To begin, please select add a question below and set it with order 0. Next,
            you can add answers to that question which can: Change your assessment variables & Lead to different
            questions depending on the a order selected.
          </p>
          <h5>Before you create any answers.</h5>
          <p>
            Make sure you're happy with your scenario variables. At the moment, updating variables after you've created
            loads of answers is much more work that it should be. We'll work on improving that in the future.
          </p>
          <h5>Question Order</h5>
          <p>The question order is a local reference to the question. Other than the first question which must have the
            order 0, it doesn't matter what order you give to a question. It must be unique within the quiz. It just
            indicates to an answer which question it should go to next.</p>
          <h5>Answer - Next Question Order</h5>
          <p>When you create an answer, you don't have to add the next question order immediately. A lot of the time you
            won't have created that next question. You can save the answer without the next question order filled in and
            come back to it later.</p>
          <h5>Last Answer - End of the scenario</h5>
          <p>If an answer is the end of the scenario click the "End of Scenario" button on the answer form.</p>
          <h5>Exploring the Quiz</h5>
          <p>Once you have a few questions and answers set up, you can explore the quiz by clicking on the "Next
            Question" button in the answer card. This will take you to the question which the answer links to. </p>
          <h5>Feedback</h5>
          <p>The app is still an early prototype. If you have any ideas, suggestions or general feedback please let us
            know!</p>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row justify-content-md-center shadow p-3 mb-5 bg-white rounded">

        <h3 class="text-center">Scenario Summary</h3>
        <div class="accordion accordion-flush" id="summary_accordion">

          <% @scenario.questions.order(:order).each do |question| %>
            <div class="accordion-item">
              <h2 class="accordion-header" id="accordion_question_order_<%= question.order %>">
                <a class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_<%= question.order %>" aria-expanded="true" aria-controls="collapse_<%= question.order %>">
                  <div class="d-flex justify-content-between align-items-center">
                    <div>Question: <%= question.order %></div>
                    <div class="accordion-question-description"><%= question.description %></div>
                    <div class="badge bg-primary rounded-pill accordion-answers-badge"><%= question.answers.count %>
                      answers
                    </div>
                  </div>
                </a>
              </h2>
              <div id="collapse_<%= question.order %>" class="accordion-collapse collapse" aria-labelledby="accordion_question_order_<%= question.order %>" data-bs-parent="#summary_accordion">
                <div class="accordion-body">
                  <h3><a href="#question_order_<%= question.order %>">Question</a></h3>
                  <p><strong><%= simple_format(question.description) %></strong></p>
                  <p><%= question.text %></p>
                  <h4>Answers</h4>
                  <div class="list-group list-group-flush">
                    <% question.answers.each do |answer| %>

                      <div class="list-group-item d-flex justify-content-between align-items-center">
                        <div class="accordion-answer-text"><%= answer.text %></div>

                        <div class="">
                          <% if answer.next_question_order.present? %>
                            <button class="btn btn-outline-primary btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_<%= answer.next_question_order %>" aria-expanded="true" aria-controls="collapse_<%= question.order %>">
                              <% if answer.next_question_order == -1 %>
                                End of Scenario
                              <% else %>
                                Links to Question <%= answer.next_question_order %>
                              <% end %>
                            </button>
                          <% else %>
                            No Next Question Set
                          <% end %>
                        </div>
                      </div>

                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <% @scenario.questions.order(:order).each do |question| %>
        <div id="question_order_<%= question.order %>"
             class="row justify-content-md-center shadow p-3 mb-5 bg-white rounded question-container">
          <div class="info-container">

            <h5 class="d-flex">Question Order: <%= question.order %>
              <span id="question_order_<%= question.order %>_help_button" class="ms-auto question_help_button"><i class="fas fa-info-circle"></i></span>
            </h5>
            <h3><span class="extra-info">Description: </span><%= simple_format(question.description) %></h3>
            <h4><span class="extra-info">Text: </span><%= question.text %></h4>
            <div class="info-alert-box">
              Above is the question info. You can see the order, the description and the text.
            </div>
          </div>

          <div class="info-container row">
            <div class="info-alert-box">
              These are the Answers that a user will be able to select from the question. You can click on the "Next
              Question" button and we'll move the page to that question.
            </div>
            <% question.answers.each do |answer| %>
              <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3 ">
                <div class="card shadow-sm mb-5 bg-white rounded">
                  <div class="card-body text-center">
                    <h5 class="card-title"><%= answer.text %></h5>
                    <% if answer.next_question_order.present? %>
                      <a href="#question_order_<%= answer.next_question_order %>" class="btn btn-outline-primary btn-sm">
                        <% if answer.next_question_order == -1 %>
                          End of Scenario
                        <% else %>
                          Next Question: <%= answer.next_question_order %>
                        <% end %>
                      </a>
                    <% else %>
                      <a href="#" class="btn btn-primary btn-sm disabled">No Next Question</a>
                    <% end %>
                  </div>
                  <div class="card-footer small ">
                    <table class="mx-auto">
                      <tr>
                        <th colspan="2"><em>Variable Modifiers:</em></th>
                        <% if answer.variable_mods.present? %>
                          <% answer.variable_mods&.each do |variable_mod| %>
                          <tr>
                            <td><%= variable_mod[0] %>:</td>
                            <td><strong><%= variable_mod[1] %></strong></td>
                          </tr>
                        <% end %>
                      <% else %>
                        <% @scenario.variables&.each do |variable| %>
                          <tr>
                            <td><%= variable %>:</td>
                            <td><strong> nil </strong></td>
                          </tr>
                        <% end %>

                      <% end %>
                      </tr>
                    </table>

                  </div>
                  <div class="card-footer text-center">
                    <%= link_to "Edit Answer", edit_scenario_question_answer_path(@scenario, question, answer), class: "btn btn-warning btn-sm" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

          <div>
            <%= link_to "Edit Question", edit_scenario_question_path(@scenario, question), class: "btn btn-warning" %>
            <%= link_to "Add New Answer", new_scenario_question_answer_path(@scenario, question), class: "btn btn-info" %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="container">
      <div class="row justify-content-md-center shadow p-3 mb-5 bg-white rounded">
        <div class="text-center">
          <%= link_to "Add new question", new_scenario_question_path(@scenario), class: "btn btn-info" %>
        </div>
      </div>
    </div>
  </section>
<% end %>

<%= javascript_pack_tag 'scenario_builder_help' %>